import React, { useState } from 'react';
import { useZKProof } from './hooks/useZKProof';
import { ContractClient } from './contracts-client'; // Generated by Stellar CLI

export default function ZeroShotGame() {
  const { generateProof } = useZKProof();
  const [status, setStatus] = useState("Waiting for move...");

  const handleDefend = async (attackX: number, attackY: number) => {
    setStatus("Generating ZK Proof of 'Miss'...");
    
    // 1. Generate Proof locally (no cost)
    const proof = await generateProof(
      {x: 5, y: 5}, // Your secret
      {x: attackX, y: attackY}, 
      "random_salt_123"
    );

    // 2. Submit to Stellar Testnet
    setStatus("Verifying on-chain via Protocol 25...");
    await ContractClient.verify_miss({
      proof: proof.proof,
      public_inputs: proof.publicInputs
    });
    
    setStatus("Verified! You successfully hid your position.");
  };

  return (
    <div className="p-8 bg-slate-900 text-white min-h-screen">
      <h1 className="text-4xl font-bold text-blue-400">ZERO-SHOT ZK</h1>
      <div className="mt-10 border-2 border-dashed p-20 text-center">
        <p>{status}</p>
        {/* Simple grid buttons to simulate being attacked */}
        <button onClick={() => handleDefend(1, 2)} className="bg-blue-600 p-4 mt-4">
          Defend Attack at (1,2)
        </button>
      </div>
    </div>
  );
}